// FFCC port: the runtime's fiber-aware OS scheduler family registered at FFCC addresses.
// Generated by ffcc-workspace/scripts/gen_ffcc_scheduler_natives.py from the Mario Kart lines;
// each wrapper keeps its original signature so the raw CpuContext thunks stay valid.
#include "hle_stubs.h"
#include "abi_bridge.h"

extern "C" [[noreturn]] void OS__LoadContext_801a1f58(CpuContext* ctx);
extern "C" void OSCancelThread_HLE_801aa1d4(CpuContext* ctx);
extern "C" void OSCreateThread_HLE_801a9e84(CpuContext* ctx);
extern "C" void OSExitThread_HLE_801aa0f0(CpuContext* ctx);
extern "C" void OSResumeThread_HLE_801aa58c(CpuContext* ctx);
extern "C" void OSSetAlarm_HLE_801a0870(CpuContext* ctx);
extern "C" void OSSleepThread_HLE_801aa9b8(CpuContext* ctx);
extern "C" void OSSuspendThread_HLE_801aa6a8(CpuContext* ctx);
extern "C" void OSWakeupThread_HLE_801aaaa4(CpuContext* ctx);
extern "C" void SelectThread_801a9c08(CpuContext* ctx);

PPC_NATIVE_OVERRIDE_VOID(80180e84, SelectThread_801a9c08, (CpuContext* ctx), (ctx));  // SelectThread (Mario Kart 0x801A9C08)
PPC_NATIVE_OVERRIDE_VOID(80181a48, OSWakeupThread_HLE_801aaaa4, (CpuContext* ctx), (ctx));  // OSWakeupThread (Mario Kart 0x801AAAA4)
PPC_NATIVE_OVERRIDE_VOID(801810dc, OSCreateThread_HLE_801a9e84, (CpuContext* ctx), (ctx));  // OSCreateThread (Mario Kart 0x801A9E84)
PPC_NATIVE_OVERRIDE_VOID(801812c4, OSExitThread_HLE_801aa0f0, (CpuContext* ctx), (ctx));  // OSExitThread (Mario Kart 0x801AA0F0)
PPC_NATIVE_OVERRIDE_VOID(801813a8, OSCancelThread_HLE_801aa1d4, (CpuContext* ctx), (ctx));  // OSCancelThread (Mario Kart 0x801AA1D4)
PPC_NATIVE_OVERRIDE_VOID(801817ec, OSSuspendThread_HLE_801aa6a8, (CpuContext* ctx), (ctx));  // OSSuspendThread (Mario Kart 0x801AA6A8)
PPC_NATIVE_OVERRIDE_VOID(80181564, OSResumeThread_HLE_801aa58c, (CpuContext* ctx), (ctx));  // OSResumeThread (Mario Kart 0x801AA58C)
PPC_NATIVE_OVERRIDE_VOID(8018195c, OSSleepThread_HLE_801aa9b8, (CpuContext* ctx), (ctx));  // OSSleepThread (Mario Kart 0x801AA9B8)
PPC_NATIVE_OVERRIDE_VOID(8017c42c, OSSetAlarm_HLE_801a0870, (CpuContext* ctx), (ctx));  // OSSetAlarm (Mario Kart 0x801A0870)
PPC_NATIVE_OVERRIDE_VOID(8017d834, OS__LoadContext_801a1f58, (CpuContext* ctx), (ctx));  // OSLoadContext (Mario Kart 0x801A1F58)
